from .boardGen import keebConfig
from .boardGen import caseConfig

choc_spacing = (18,17)
mx_spacing = (19.05, 19.05)

config_36 = keebConfig(
    height_plate = 1.2,
    height_mid = 2,
    height_pcb = 1.6,
    spacing = choc_spacing,
    hSize = (14,14),
    rows =  3,
    cols = 5,
    keysPerCol= ( 3, 3, 3, 3, 3 ),
    stagger= ( 0, 2, 6, 2,-7 ),
    colRot= (0,0,0,0,0),
    tClusterRot= (36, 15, -4),
    tClusterPos= (1,5),
    tClusterSpacing= 5,
    handRotation= 18,
    handDistance = 25,
    holeToEdge = 3,
    doFillet= True,
    filletSizeLarge= 5,
    filletSizeSmall= 3,
    startCorrection = 1,
    outerThumb1u5 = False,
    )

config_36_mx = keebConfig(
    height_plate = 1.2,
    height_mid = 2,
    height_pcb = 1.6,
    spacing = mx_spacing,
    hSize = (14,14),
    rows =  3,
    cols = 5,
    keysPerCol= ( 3, 3, 3, 3, 3 ),
    stagger= ( 0, 2, 6, 2,-7),
    colRot= (0,0,0,0,0),
    tClusterRot= (36, 15, -4),
    tClusterPos= (1,5),
    tClusterSpacing= 5.5,
    handRotation= 17,
    handDistance = 25,
    holeToEdge = 3,
    doFillet= True,
    filletSizeLarge= 5,
    filletSizeSmall= 3,
    startCorrection = 1,
    outerThumb1u5 = False,
    )

config_32_g = keebConfig(
    height_plate = 1.2,
    height_mid = 2,
    height_pcb = 1.6,
    spacing = choc_spacing,
    hSize = (14,14),
    rows =  3,
    cols = 5,
    keysPerCol= ( 3, 3, 3, 3, 2 ),
    stagger= ( 0, 2, 6, 2,-7+choc_spacing[1]),
    colRot= (0,0,0,0,0),
    tClusterRot= (36, 15),
    tClusterPos= (1,7),
    tClusterSpacing= 7,
    handRotation= 18,
    handDistance = 25,
    holeToEdge = 4,
    doFillet= True,
    filletSizeLarge= 5,
    filletSizeSmall= 3,
    startCorrection = 2.5,
    outerThumb1u5 = True,
    upperEdgeOffset = 4.5,
    )

config_36_test = keebConfig(
    height_plate = 1.2,
    height_mid = 2,
    height_pcb = 1.6,
    spacing = choc_spacing,
    hSize = (14,14),
    rows =  3,
    cols = 5,
    keysPerCol= ( 3, 3, 3, 3, 3 ),
    stagger= ( 0, 2, 6, 2,-7 ),
    colRot= (0,0,0,0,0),
    tClusterRot= (36, 15, -4),
    tClusterPos= (1,7),
    tClusterSpacing= 7,
    handRotation= 18,
    handDistance = 20,
    holeToEdge = 4,
    doFillet= True,
    filletSizeLarge= 5,
    filletSizeSmall= 3,
    startCorrection = -3,
    outerThumb1u5 = True,
    upperEdgeOffset = 5,
    )

config_32 = keebConfig(
    height_plate = 1.2,
    height_mid = 2,
    height_pcb = 1.6,
    spacing = choc_spacing,
    hSize = (14,14),
    rows =  3,
    cols = 5,
    keysPerCol= ( 3, 3, 3, 3, 2 ),
    stagger= ( 0, 2, 6, 2,-7+choc_spacing[1]),
    colRot= (0,0,0,0,0),
    tClusterRot= (36, 15),
    tClusterPos= (1,7),
    tClusterSpacing= 7,
    handRotation= 18,
    handDistance = 20,
    holeToEdge = 3,
    doFillet= True,
    filletSizeLarge= 5,
    filletSizeSmall= 5,
    startCorrection = 2.5,
    outerThumb1u5 = True,
    upperEdgeOffset = 5,
    )

config_32_f = keebConfig(
    height_plate = 1.2,
    height_mid = 2,
    height_pcb = 1.6,
    spacing = choc_spacing,
    hSize = (14,14),
    rows =  3,
    cols = 5,
    keysPerCol= ( 3, 3, 3, 3, 3 ),
    stagger= ( 0, 2, 6, 2,-7 ),#+choc_spacing[1]),
    colRot= (0,0,0,0,0),
    tClusterRot= (20,10),
    tClusterPos= (1,6),
    tClusterSpacing= 7,
    handRotation= 18,
    handDistance = 20,
    holeToEdge = 3,
    doFillet= True,
    filletSizeLarge= 5,
    filletSizeSmall= 5,
    startCorrection = 2.5,
    outerThumb1u5 = True,
    upperEdgeOffset = 3,
    )

config_lowProfile = caseConfig(
    switchClearance = 5.2,
    clearanceSafety = 1,
    wallSafety = 0.5,
    wallThickness = 2,
    heightAbovePlate = 0,
    cutoutExtra = (1, 1)
    )

config_highProfileChoc = caseConfig(
    switchClearance = 5.2,
    clearanceSafety = 1,
    wallSafety = .5,
    wallThickness = 2,
    heightAbovePlate = 5,
    cutoutExtra = (0.25, 0.25 )
    )
